### ISSUE TITLE
Thoughts on Reor?

### ISSUE THREAD

**Issue by samlhuillier** [pachacamac/pachacamac#2]
Did you get a chance to try [Reor](https://github.com/reorproject/reor)? Would love your thoughts...

**Comment by pachacamac** [comment]
Oh wow apologies, I totally did not see this. Reor looks super interesting. Similar to Obsidian with LLM plugins. However it got stuck for me on 
<img width="595" alt="image" src="https://github.com/user-attachments/assets/9459303b-1f50-4374-969c-27a75360138f">

PS: with an empty data folder

**Comment by pachacamac** [comment]
Alright after killing and restarting it seemed to work. Some things I immediately find:

- I created a few example notes (tech, cooking, gardening, etc) and used the chat to ask some questions
- Even though those were only 4-5 very distinct topics it consistently got the context wrong and pulled e.g. my "app building thoughts" doc instead of my "quick food recipe ideas" doc into a chat convo where I said "I'm hungry"
- The chat is not stoppable! This gets so annoying because the model (in this case llama3.1 8b) can occasionally blabber on about the wrong stuff and not being able to stop it is incredibly annoying.
